### ISSUE TITLE
怎么在左侧标题栏加入作者的信息，比如头像

### ISSUE THREAD

**Issue by shujikemobile** [zhangjikai/gitbook-use#8]
怎么在左侧标题栏加入作者的信息，比如头像

**Comment by zhangjikai** [comment]
去插件库看了一下，没有找到相关的插件，不过可以通过修改模板文件来实现这个功能。下面是一个示例：
* 首先找到 gitbook 默认主题存放的目录，一般是在 `<user_home>/.gitbook/versions/<version_tag>/node_modules/gitbook-plugin-theme-default` 文件夹下。
* 打开 `_layout/website/summary.html`，该文件是左侧标题栏的布局文件，我们在该文件中加入下面的内容
```html
<ul class="summary">
    <!-- 在这里添加展示作者信息的 html  -->
    <div class="author">
        <div class="avatar">
            <img src="http://www.zhangjikai.com/home/images/avatar.jpg">
        </div>
        <p class="author-name">Author Name</p>
        <li class="divider"></li>
    </div>
    
    {% set _divider = false %}
    <!-- 省略后面的代码 -->
</ul>
```
* 然后在项目中的  `styles/website.css`  文件中加入下面的样式：
```css
.author {
	text-align: center;
}

.author .avatar img {
	border: 0;
	border-radius: 50%;
}

.author .author-name {
	margin: 5px;
	font-size: 1em;
	color: #044f67;
}
```
* 效果如下图所示：
![](https://user-images.githubusercontent.com/10095634/33646316-dfaec752-da89-11e7-9b06-69a3afcbd9a0.png)

---
如果感觉这样做太麻烦，可以去 [GitBook 的项目下](https://github.com/GitbookIO/gitbook) 去提 issue，看看有没有更简便的方法。
